version: '2'
services:
  pap:
    container_name: argus-pap-centos6.cnaf.test
    hostname: argus-pap-centos6
    domainname: cnaf.test
    build: ./pap/
    image: ${REGISTRY}italiangrid/argus-pap-centos6
    ports:
      - "8150:8150"
      - "8151:8150"
    environment:
      FACTER_ARGUS_REPO_BASE_URL: ${FACTER_ARGUS_REPO_BASE_URL}


  pdp:
    container_name: argus-pdp-centos6.cnaf.test
    hostname: argus-pdp-centos6
    domainname: cnaf.test
    build: ./pdp/
    image: ${REGISTRY}italiangrid/argus-pdp-centos6
    ports:
      - "8152:8152"
      - "8153:8153"
    depends_on:
      - pap
    environment:
      PAP_HOST: argus-pap-centos6.cnaf.test
      PAP_PORT: 8150
      FACTER_ARGUS_REPO_BASE_URL: ${FACTER_ARGUS_REPO_BASE_URL}


  pep:
    container_name: argus-pep-centos6.cnaf.test
    hostname: argus-pep-centos6
    domainname: cnaf.test
    build: ./pep/
    image: ${REGISTRY}italiangrid/argus-pep-centos6
    ports:
      - "8154:8154"
      - "8155:8155"
    depends_on:
      - pdp
    environment:
      PDP_HOST: argus-pdp-centos6.cnaf.test
      PDP_PORT: 8152
      FACTER_ARGUS_REPO_BASE_URL: ${FACTER_ARGUS_REPO_BASE_URL}


  bdii:
    container_name: argus-bdii-centos6.cnaf.test
    hostname: argus-bdii-centos6
    domainname: cnaf.test
    build: ./bdii/
    image: ${REGISTRY}italiangrid/argus-bdii-centos6
    ports:
      - "2170:2170"
    depends_on:
      - pap
      - pdp
      - pep

