version: '2'
services:
  pap:
    container_name: argus-pap-centos6.cnaf.test
    hostname: argus-pap-centos6
    domainname: cnaf.test
    build: ./pap/
    image: argus-pap-centos6
    ports:
      - "8150:8150"
      - "8151:8150"
      - "9012:9012"
      - "4002:4002"
    volumes:
      - /dev/urandom:/dev/random
    environment:
      ENABLE_JMX: y
      JMX_PORT: 9012
      ENABLE_DEBUG: y
      DEBUG_PORT: 4002


  pdp:
    container_name: argus-pdp-centos6.cnaf.test
    hostname: argus-pdp-centos6
    domainname: cnaf.test
    build: ./pdp/
    image: argus-pdp-centos6
    ports:
      - "8152:8152"
      - "8153:8153"
      - "9011:9011"
      - "4001:4001"
    depends_on:
      - pap
    volumes:
      - /dev/urandom:/dev/random
    environment:
      ENABLE_JREBEL: y
      ENABLE_JMX: y
      JMX_PORT: 9011
      ENABLE_DEBUG: y
      DEBUG_PORT: 4001
      PAP_HOST: argus-pap-centos6.cnaf.test
      PAP_PORT: 8150


  pep:
    container_name: argus-pep-centos6.cnaf.test
    hostname: argus-pep-centos6
    domainname: cnaf.test
    build: ./pep/
    image: argus-pep-centos6
    ports:
      - "8154:8154"
      - "8155:8155"
      - "9010:9010"
      - "4000:4000"
    depends_on:
      - pdp
    volumes:
      - /dev/urandom:/dev/random
    environment:
      ENABLE_JREBEL: y
      ENABLE_JMX: y
      JMX_PORT: 9010
      ENABLE_DEBUG: y
      DEBUG_PORT: 4000
      PDP_HOST: argus-pdp-centos6.cnaf.test
      PDP_PORT: 8152


  bdii:
    container_name: argus-bdii-centos6.cnaf.test
    hostname: argus-bdii-centos6
    domainname: cnaf.test
    build: ./bdii/
    image: argus-bdii-centos6
    ports:
      - "2170:2170"
    depends_on:
      - pap
      - pdp
      - pep

